Database exception: PDOException: PDO::__construct(): php_network_getaddresses: getaddrinfo for db failed: nodename nor servname provided, or not known in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:23
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(23): PDO->__construct('mysql:host=db;p...', 'root', Object(SensitiveParameterValue))
#1 /Users/user/Sites/test.local/index.php(11): App\repositories\TaskRepository->__construct()
#2 {main}

Next PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for db failed: nodename nor servname provided, or not known in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:23
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(23): PDO->__construct('mysql:host=db;p...', 'root', Object(SensitiveParameterValue))
#1 /Users/user/Sites/test.local/index.php(11): App\repositories\TaskRepository->__construct()
#2 {main}
Database exception: PDOException: PDO::__construct(): php_network_getaddresses: getaddrinfo for db failed: nodename nor servname provided, or not known in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:23
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(23): PDO->__construct('mysql:host=db;p...', 'root', Object(SensitiveParameterValue))
#1 /Users/user/Sites/test.local/index.php(11): App\repositories\TaskRepository->__construct()
#2 {main}

Next PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for db failed: nodename nor servname provided, or not known in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:23
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(23): PDO->__construct('mysql:host=db;p...', 'root', Object(SensitiveParameterValue))
#1 /Users/user/Sites/test.local/index.php(11): App\repositories\TaskRepository->__construct()
#2 {main}
Database exception: PDOException: PDO::__construct(): php_network_getaddresses: getaddrinfo for db failed: nodename nor servname provided, or not known in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:23
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(23): PDO->__construct('mysql:host=db;p...', 'root', Object(SensitiveParameterValue))
#1 /Users/user/Sites/test.local/index.php(11): App\repositories\TaskRepository->__construct()
#2 {main}

Next PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for db failed: nodename nor servname provided, or not known in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:23
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(23): PDO->__construct('mysql:host=db;p...', 'root', Object(SensitiveParameterValue))
#1 /Users/user/Sites/test.local/index.php(11): App\repositories\TaskRepository->__construct()
#2 {main}
Database exception: PDOException: PDO::__construct(): php_network_getaddresses: getaddrinfo for mysql failed: nodename nor servname provided, or not known in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:23
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(23): PDO->__construct('mysql:host=mysq...', 'root', Object(SensitiveParameterValue))
#1 /Users/user/Sites/test.local/index.php(11): App\repositories\TaskRepository->__construct()
#2 {main}

Next PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for mysql failed: nodename nor servname provided, or not known in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:23
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(23): PDO->__construct('mysql:host=mysq...', 'root', Object(SensitiveParameterValue))
#1 /Users/user/Sites/test.local/index.php(11): App\repositories\TaskRepository->__construct()
#2 {main}
Database exception: PDOException: PDO::__construct(): php_network_getaddresses: getaddrinfo for mysql failed: nodename nor servname provided, or not known in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:23
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(23): PDO->__construct('mysql:host=mysq...', 'root', Object(SensitiveParameterValue))
#1 /Users/user/Sites/test.local/index.php(11): App\repositories\TaskRepository->__construct()
#2 {main}

Next PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for mysql failed: nodename nor servname provided, or not known in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:23
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(23): PDO->__construct('mysql:host=mysq...', 'root', Object(SensitiveParameterValue))
#1 /Users/user/Sites/test.local/index.php(11): App\repositories\TaskRepository->__construct()
#2 {main}
Database exception: PDOException: PDO::__construct(): php_network_getaddresses: getaddrinfo for mysql failed: nodename nor servname provided, or not known in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:23
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(23): PDO->__construct('mysql:host=mysq...', 'root', Object(SensitiveParameterValue))
#1 /Users/user/Sites/test.local/index.php(11): App\repositories\TaskRepository->__construct()
#2 {main}

Next PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for mysql failed: nodename nor servname provided, or not known in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:23
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(23): PDO->__construct('mysql:host=mysq...', 'root', Object(SensitiveParameterValue))
#1 /Users/user/Sites/test.local/index.php(11): App\repositories\TaskRepository->__construct()
#2 {main}
Database exception: PDOException: PDO::__construct(): php_network_getaddresses: getaddrinfo for mysql failed: nodename nor servname provided, or not known in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:23
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(23): PDO->__construct('mysql:host=mysq...', 'root', Object(SensitiveParameterValue))
#1 /Users/user/Sites/test.local/index.php(11): App\repositories\TaskRepository->__construct()
#2 {main}

Next PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for mysql failed: nodename nor servname provided, or not known in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:23
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(23): PDO->__construct('mysql:host=mysq...', 'root', Object(SensitiveParameterValue))
#1 /Users/user/Sites/test.local/index.php(11): App\repositories\TaskRepository->__construct()
#2 {main}
Database exception: PDOException: PDO::__construct(): php_network_getaddresses: getaddrinfo for mysql failed: nodename nor servname provided, or not known in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:23
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(23): PDO->__construct('mysql:host=mysq...', 'root', Object(SensitiveParameterValue))
#1 /Users/user/Sites/test.local/index.php(11): App\repositories\TaskRepository->__construct()
#2 {main}

Next PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for mysql failed: nodename nor servname provided, or not known in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:23
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(23): PDO->__construct('mysql:host=mysq...', 'root', Object(SensitiveParameterValue))
#1 /Users/user/Sites/test.local/index.php(11): App\repositories\TaskRepository->__construct()
#2 {main}
Database exception: PDOException: PDO::__construct(): php_network_getaddresses: getaddrinfo for db failed: nodename nor servname provided, or not known in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:23
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(23): PDO->__construct('mysql:host=db;p...', 'root', Object(SensitiveParameterValue))
#1 /Users/user/Sites/test.local/index.php(11): App\repositories\TaskRepository->__construct()
#2 {main}

Next PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for db failed: nodename nor servname provided, or not known in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:23
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(23): PDO->__construct('mysql:host=db;p...', 'root', Object(SensitiveParameterValue))
#1 /Users/user/Sites/test.local/index.php(11): App\repositories\TaskRepository->__construct()
#2 {main}
Database exception: PDOException: SQLSTATE[HY000] [2002] Operation timed out in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:23
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(23): PDO->__construct('mysql:host=172....', 'root', Object(SensitiveParameterValue))
#1 /Users/user/Sites/test.local/index.php(11): App\repositories\TaskRepository->__construct()
#2 {main}
Database exception: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'task_id' in 'where clause' in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:54
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(54): PDOStatement->execute(Array)
#1 /Users/user/Sites/test.local/src/controllers/APIController.php(68): App\repositories\TaskRepository->findTaskById('19')
#2 /Users/user/Sites/test.local/index.php(30): App\controllers\APIController->handleGetRequest('19')
#3 {main}
Database exception: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'task_id' in 'field list' in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:67
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(67): PDOStatement->execute(Array)
#1 /Users/user/Sites/test.local/src/controllers/APIController.php(30): App\repositories\TaskRepository->findTaskByPhotoAndName('Inna', '')
#2 /Users/user/Sites/test.local/index.php(39): App\controllers\APIController->handlePostRequest('Inna', Object(CURLFile))
#3 {main}
Database exception: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'photo_path' in 'field list' in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:34
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(34): PDOStatement->execute(Array)
#1 /Users/user/Sites/test.local/src/controllers/APIController.php(41): App\repositories\TaskRepository->createTask('Inna', 'photo1.jpg', '/var/folders/bn...')
#2 /Users/user/Sites/test.local/index.php(45): App\controllers\APIController->handlePostRequest('Inna', Array)
#3 {main}
Database exception: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'photo_path' in 'field list' in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:34
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(34): PDOStatement->execute(Array)
#1 /Users/user/Sites/test.local/src/controllers/APIController.php(41): App\repositories\TaskRepository->createTask('Inna', 'photo2.jpg', '/var/folders/bn...')
#2 /Users/user/Sites/test.local/index.php(45): App\controllers\APIController->handlePostRequest('Inna', Array)
#3 {main}
Database exception: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'photo_path' in 'field list' in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:34
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(34): PDOStatement->execute(Array)
#1 /Users/user/Sites/test.local/src/controllers/APIController.php(41): App\repositories\TaskRepository->createTask('Inna', 'photo2.jpg', '/Users/user/Sit...')
#2 /Users/user/Sites/test.local/index.php(45): App\controllers\APIController->handlePostRequest('Inna', Array)
#3 {main}
Database exception: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'photo_path' in 'field list' in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:34
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(34): PDOStatement->execute(Array)
#1 /Users/user/Sites/test.local/src/controllers/APIController.php(41): App\repositories\TaskRepository->createTask('Inna', 'photo2.jpg', '/Users/user/Sit...')
#2 /Users/user/Sites/test.local/index.php(45): App\controllers\APIController->handlePostRequest('Inna', Array)
#3 {main}
Database exception: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'task_id' in 'where clause' in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:55
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(55): PDOStatement->execute(Array)
#1 /Users/user/Sites/test.local/src/controllers/APIController.php(70): App\repositories\TaskRepository->findTaskById('1')
#2 /Users/user/Sites/test.local/index.php(48): App\controllers\APIController->handleGetRequest('1')
#3 {main}
Database exception: PDOException: SQLSTATE[HY000] [2002] Connection refused in /Users/user/Sites/test.local/src/repositories/TaskRepository.php:23
Stack trace:
#0 /Users/user/Sites/test.local/src/repositories/TaskRepository.php(23): PDO->__construct('mysql:host=0.0....', 'root', Object(SensitiveParameterValue))
#1 /Users/user/Sites/test.local/index.php(11): App\repositories\TaskRepository->__construct()
#2 {main}
